language: node_js
node_js: 
  - node
before_script:
  - python -m SimpleHTTPServer &
  - sleep 2
script: "PORT=8080 npm test"
addons:
  sauce_connect: true
sudo: false
env:
  global:
    - secure: "ZbRrkSl4Xky5/Zk28gPozaR13bolqG8yjZpqXPa2Dttb8/+t8NRLncy2Y9D6OUkHD/7fAL6e6CNxOzx4FAJTw54aHMdyutC4qk/N8F289NO8doDxJFF5OTVjQsXYqFY6RPDETLe2NIHhlB5KcuwrrysyQ5ZgasitqmIbWeiZ06Qn1V4lw+KVpGZomTf7rFYuug/VcghloLfKp78kKfDyxg2hHzcfS/TTMEc9qrq6OxkEkvqMRoeXIGVTufMmciUEvm19zwq+XmC548cs6jhFwMYnj0bDYFy4R/ROuSRT1PYUHjgooGTtbyOQLIB6h7Q5iTQvn0TypC1lGE5OESWR8811RmKXF+21ZO2wlXv+Eh13W6l3q9XRet+e8D7gW5UAn6v5B6aFFwhOSer8p28NCgoOh5QbJwGE+4r7H2E/LxfqwIg/CtSZ2p2QTwinThHuM4SHR/q5Vblxnj8Oo7LBp7cpLeftH33F3FGSAdxTImP/b+u4E9m/6uKAah4shEzJF8EKMVtF4ouJs3BgNZO1qLSxT8CKJbmCoF3394tlu7V/qiovQ3HZv2UgRlWEqk0KPL/mQ1JP59whBMhUlZi0BZft+7r4mnn3pV/4or8CV2bkIRo9ovjnzj1qp1stUDhFe1TpZ3EOrhFRppykTZbg9n35RtxD0+pdjKd9PLQD/3I="
    - secure: "qYYLjzsJfPrWxDy3aVXXA5DWZlJIo/m7wvidXk9GHRH2tcFlnl7Od5XttKQ57YJlWmCbUNfnOFkxBB4tcZrIXb+QC7JZYr776h24R8tSWgVzXF7V3NZFOTp1ShMkvf7lWcpU56bJifhLZ+TKJ9z44kjfgayU1EZVzd/WIMa25FNpsbqRALYJtc5SxHiLOUztS4M/LvuASlCzs2DPelID3Ep2ITyW+KT+xAS+Wis9Xj16sqvoCX/gozGi7R7XXKBkp20yzGzykxAUb/LRrfrGDK4k3A7EHtJkyaGpNntHJPzXoP8vPE1Fts/+IydUoF8VvYOncKQ64Vjfd0fUSkfq9kleYJFsQvV+9ltGlthY5srbLQuNzaz0O/2vCSmNVx8IfU5m93OkxgzuREPuKtRyiS408/hUZtSrQgQpbJqBRQfzrq4ZDO4u/38UQ+fQHi2wB97LXCm8Ddqa+SO3HgMbkZSyG+uWHrGABOihjuZhbqIPq46zk7S0hPALaH3OxOpxDBVsfKpQSJHoRXju533jliCLfbzBeQKe6EyxAJfMI5ntnLwbjOwqdpMVnVrjcnLXtsHngVVXxu+vVl06w3+Ae+6nyuBDqVzTXYKFPjfrMhVOT3mB1Bsz+QdLHShSW3eu0wKJv7NR/uH/UBWCHuuNxwXdR0MYN4lqvwY7I6Ys+/Y="
